# Generated by Django 4.2 on 2023-04-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_firstaid_remove_video_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.CharField(default='No description available', max_length=255),
        ),
    ]
