# Generated by Django 4.2 on 2023-04-12 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_video_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='firstaid',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
