# Generated by Django 4.2 on 2023-04-12 13:33

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_articles_id_alter_firstaid_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
    ]
